### ISSUE TITLE
act-r-sentence-parser-em does not work with latest ccl 1.11

### ISSUE THREAD

**Issue by lopuhin** [felixengelmann/act-r-sentence-parser-em#3]
The error is `The function CHOOSE-FILE-DIALOG is predefined in
Clozure CL`, see http://mailman.srv.cs.cmu.edu/pipermail/act-r-users/2016-March.txt

I think it would be nice to mention that in README and update Max OS X installation instructions: version from the App Store no longer works, what worked for us was to download ftp://ftp.clozure.com/pub/release/1.10/ccl-1.10-darwinx86.tar.gz, unpack it and just run `dx86cl64` from there.

Shall I can send a PR with updated README?

**Comment by felixengelmann** [comment]
Thanks! I updated it in the README.
